# Site settings
title: web2project Documentation

# Exclude our ruby stuff
exclude: [Gemfile, Gemfile.lock, README.md]

collections:
  all:
    output: true
  modules:
    output: true
  docs:
    output: true
  release-notes:
    output: true